fix(gateway-helm): requested changes

diff --git a/helm-charts/infisical-gateway/templates/deployment.yaml b/helm-charts/infisical-gateway/templates/deployment.yaml
--- a/helm-charts/infisical-gateway/templates/deployment.yaml
+++ b/helm-charts/infisical-gateway/templates/deployment.yaml
@@ -35,8 +35,16 @@ spec:
           securityContext:
             {{- toYaml . | nindent 12 }}
           {{- end }}
-          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
+          image: "infisical/cli:{{ .Values.image.tag | default .Chart.AppVersion }}"
           imagePullPolicy: {{ .Values.image.pullPolicy }}
+          command: ["/sbin/tini", "--", "/bin/sh", "-c"]
+          args:
+            - >-
+              if [ -z "${TOKEN}" ]; then 
+                echo 'ERROR: TOKEN environment variable must be set'; 
+                exit 1; 
+              fi && 
+              /bin/infisical gateway --token ${TOKEN}
           envFrom:
             - secretRef:
                 name: {{ .Values.secret.name }}
